In [1]:
import numpy as np

In [2]:
np.___version__

AttributeError: module 'numpy' has no attribute '___version__'

In [3]:
np.__version__

'1.26.4'

In [4]:
np.add(1,1)

2

In [6]:
a = np.array([1,3,5])

In [7]:
a

array([1, 3, 5])

In [8]:
a.shape

(3,)

In [10]:
a.ndim

1

In [14]:
b = np.array([[1,3,5],[4,6,8]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [17]:
b

array([[1, 3, 5],
       [4, 6, 8]])

In [37]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [38]:
c.ndim

3

In [39]:
c.shape

(1, 3, 3)

In [40]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [41]:
d=np.array([[[[1,2,3],[4,6,5]]]])

In [42]:
d.shape

(1, 1, 2, 3)

In [48]:
array = np.array([1,2,3,4,5])

In [50]:
print(array[2])

3


In [51]:
array

array([1, 2, 3, 4, 5])

In [53]:
print(array[1])

2


In [55]:
g = np.array([[1,2,3,4],[4,6,9,7]])

In [56]:
g

array([[1, 2, 3, 4],
       [4, 6, 9, 7]])

In [58]:
print (g[0,2])

3


In [59]:
print(g[1,2])


9


In [60]:
n=np.array([[[1,2,3,4,5],[7,5,6,9,2],[1,0,5,9,3]]])

In [61]:
n

array([[[1, 2, 3, 4, 5],
        [7, 5, 6, 9, 2],
        [1, 0, 5, 9, 3]]])

In [62]:
print(n[0,1,3])

9


In [65]:
k=np.array([[[1,3,5],[4,6,7]],[[0,6,8],[8,9,5]]])
k

array([[[1, 3, 5],
        [4, 6, 7]],

       [[0, 6, 8],
        [8, 9, 5]]])

In [68]:
print(k[1,0,1])

6


In [69]:
print(k[1,0,0])

0


In [70]:
p = np.array([1,5,8,7,6])

In [71]:
p


array([1, 5, 8, 7, 6])

In [75]:
print(p[-3:])

[8 7 6]


In [77]:
print(p[2:])

[8 7 6]


In [79]:
w = np.array([1,2,3,4,5,6,7,8,9,10])
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
print(w[0::2])


[1 3 5 7 9]


In [82]:
print(w[:3:2])

[1 3]


In [84]:
print(w.dtype)

int32


In [85]:
k= w.astype(float)

In [86]:
k

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [87]:
l = np.array(['f','s','g','v','e'])

In [88]:
print(l.dtype)

<U1


In [90]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [91]:
arr.shape

(12,)

In [92]:
arr_new = arr.reshape(4,3)

In [93]:
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
a = np.array([[1,3,5,4],[4,6,5,3]])

In [95]:
a

array([[1, 3, 5, 4],
       [4, 6, 5, 3]])

In [96]:
a_new = a.reshape(-1)

In [97]:
a_new

array([1, 3, 5, 4, 4, 6, 5, 3])

In [98]:
print(a_new)

[1 3 5 4 4 6 5 3]


In [99]:
b = np.array([1,2,3,4,5])

In [100]:
for x in b:
    print(x)

1
2
3
4
5


In [105]:
d = np.array([[1,3,5,4],[4,6,5,3]])
for i  in d:
    for j in i:
        print(j)

1
3
5
4
4
6
5
3


In [107]:
n=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
for x in n:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [108]:
x = np.zeros((2,2))

In [109]:
x

array([[0., 0.],
       [0., 0.]])

In [111]:
y = np.ones((2,2))
y

array([[1., 1.],
       [1., 1.]])

In [120]:
from numpy import random
x=random.randint(100,size=(6,8))
x

array([[78, 55,  5, 42, 27, 64, 15, 69],
       [38, 89, 14, 95, 75, 16, 92, 27],
       [11, 96, 56, 10, 12, 13, 54, 90],
       [58, 93, 30, 88, 60, 58, 36,  2],
       [99, 37, 38, 84, 62, 65, 86, 37],
       [28, 73, 45, 69, 97, 60, 90, 99]])

In [122]:
y=random.choice([5,6,3,4,9],size=(3,4))
y

array([[9, 5, 9, 4],
       [6, 9, 5, 6],
       [5, 6, 9, 9]])

In [123]:
u = random.choice(100,size=(2,5))

In [124]:
u

array([[ 2, 86,  4,  4, 13],
       [13, 54, 85, 63,  3]])

In [134]:
s= np.ones((3,3,2))
s

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [135]:
s.shape

(3, 3, 2)

In [137]:
a = np.array([[1,2,3,4],[4,5,6]])
for i in a:
    i = a/2
print(i)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
